server:
  port: 7904
spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/star_red_hot'
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    max-active: 10
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evicable-idle-time-millis: 30000
    validation-query: select 'x'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
security:
  user:
    name: gaolin
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:7906/eureka/
  instance:
    status-page-url: http://127.0.0.1:${server.port}/swagger-ui.html

